---
title: "summary_stats"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(fasterize)
library(lwgeom)
library(broom)
library(jtools)
library(dplyr)
library(kableExtra)
library(rgdal)
library(rgeos)
library(maptools)
library(spData)

```

Read in AREA tables
```{r}

#read in area stats

#strongholds
strong_terr <- read_csv("strong_area.csv")%>%
  clean_names()

strong_sum_km <- summarise(strong_terr, sum_sq_km = sum(sq_km))%>% 
  mutate(perc_tot = (sum_sq_km/148939063)*100)

strong_sum_mile <- summarise(strong_terr, sum_sq_mile = sum(sq_mile))

#strongholds with WWW
strong_www_terr <- read_csv("strong_www_area.csv")%>%
  clean_names()

strong_www_sum_km <- summarise(strong_www_terr, sum_sq_km = sum(sq_km))%>% 
  mutate(perc_tot = (sum_sq_km/148939063)*100)

strong_www_sum_mile <- summarise(strong_www_terr, sum_sq_miles = sum(sq_miles))


#WWW
www_terr <- read_csv("www_area.csv")%>%
  clean_names()

www_sum_km <- summarise(www_terr, sum_sq_km = sum(sq_km)) %>% 
  mutate(perc_tot = (sum_sq_km/148939063)*100)

www_sum_mile <- summarise(www_terr, sum_sq_mile = sum(sq_mile))


```

Species Richness
```{r}

#read in sr tables
strong_sr <- read_csv("strong_sr_table.csv") %>% 
  clean_names()

strong_mean_sr <- strong_sr %>% 
  mutate(mean_sd = mean(std)) %>% 
  mutate(mean_sr = mean(mean))

#strong with WWW
strong_www_sr <- read_csv("strong_www_sr.csv") %>% 
  clean_names()

strong_www_mean_sr <- strong_www_sr %>% 
  mutate(mean_sd = mean(std)) %>% 
  mutate(mean_sr = mean(mean))

#www
www_sr <- read_csv("www_sr_table.csv") %>% 
  clean_names()

www_mean_sr <- www_sr %>% 
  mutate(mean_sd = mean(std)) %>% 
  mutate(mean_sr = mean(mean))

```

Threatened Species
```{r}

#read in the threat tables
strong_threat <- read_csv("strong_threat_table.csv") %>% 
  clean_names()

strong_mean_threat <- strong_threat %>% 
  mutate(mean_sd = mean(std)) %>% 
  mutate(mean_threat = mean(mean))

#strongholds with www
strong_www_threat <- read_csv("strong_www_threat.csv") %>% 
  clean_names()

strong_www_mean_threat <- strong_www_threat %>% 
  mutate(mean_sd = mean(std)) %>% 
  mutate(mean_threat = mean(mean))


#www
www_threat <- read_csv("www_threat_table.csv") %>% 
  clean_names()

www_mean_threat<- www_threat %>% 
  mutate(mean_sd = mean(std)) %>% 
  mutate(mean_threat = mean(mean))

```

Protected Areas
```{r}

#all strongholds
strong_pa <- read_csv("strong_pa.csv") %>% 
  clean_names  %>% 
  filter(sq_km > 0) %>% 
  mutate(pa_def = 1)

strong_pa_name_km <- strong_pa %>% 
  group_by(name) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km)) %>% 
  mutate(perc_km = sum(sq_km)/strong_sum_km$sum_sq_km)

strong_pa_iucn_km <- strong_pa %>% 
  group_by(iucn_cat) %>% 
  summarise(sum(sq_km))

strong_pa_iucn_poly <- strong_pa %>% 
  group_by(iucn_cat) %>% 
  summarise(sum(pa_def))

#strongholds with www areas
strong_www_pa <- read_csv("strong_www_pa.csv") %>% 
  clean_names  %>% 
  filter(sq_km > 0) %>% 
  mutate(pa_def = 1)

strong_www_pa_name_km <- strong_www_pa %>% 
  group_by(name) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km)) %>% 
  mutate(perc_km = sum(sq_km)/strong_www_sum_km$sum_sq_km)

strong_www_pa_iucn_km <- strong_www_pa %>% 
  group_by(iucn) %>% 
  summarise(sum(sq_km))

strong_www_pa_iucn_poly <- strong_www_pa %>% 
  group_by(iucn) %>% 
  summarise(sum(pa_def))

#only www areas
www_pa <- read_csv("www_pa.csv") %>% 
  clean_names %>% 
  filter(sq_km > 0)

www_pa_name_km <- www_pa %>% 
  group_by(name) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km)) %>% 
  mutate(perc_km = sum(sq_km)/www_sum_km$sum_sq_km)

www_pa_iucn_km <- www_pa %>% 
  group_by(iucn_cat_c_20) %>% 
  summarise(sum(sq_km)) %>% 
  mutate(total_sq_km = sum(sq_km))

www_pa_iucn_poly <- www_pa %>% 
  group_by(iucn_cat_c_20) %>% 
  summarise(sum(pa_def_c_20))

  #mutate(name = unique(name))
  #summarise_all(funs(toString(na.omit(.))))
  

```

Integrity
```{r}

#


```

KBAs
```{r}

#global KBAs
global_kba <- read_csv("global_kba.csv") %>% 
  clean_names() %>% 
  filter(sq_km > 0) %>%
  group_by(country) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km))

#strongholds with KBAs
strong_kba <- read_csv("strong_KBA.csv") %>% 
  clean_names() %>%
  filter(sq_km > 0) %>%
  group_by(fid_global) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km)) %>% 
  mutate(perc_total_kba = sum_sq_km/global_kba$sum_sq_km)

#strongholds with WWW and KBAs
strong_www_kba <- read_csv("strong_www_KBA.csv") %>% 
  clean_names() %>%
  filter(sq_km > 0) %>%
  group_by(fid_globa) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km)) %>% 
  mutate(perc_total_kba = sum_sq_km/global_kba$sum_sq_km)

#www with KBAs
www_kba <- read_csv("www_KBA.csv") %>% 
  clean_names() %>%
  filter(sq_km > 0) %>%
  group_by(fid_global) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km)) %>% 
  mutate(perc_total_kba = sum_sq_km/global_kba$sum_sq_km)

```

Threatened Ecoregions: WWF Global 200
```{r}

#strongholds
strong_g200_terr <- read_csv("strong_g200_terr_table.csv") %>% 
  clean_names() %>%
  rename(sq_km = sq_km_20) %>% 
  filter(sq_km > 0) %>%
  group_by(objectid) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km))

#strongholds with WWW
strong_www_g200_terr <- read_csv("strong_www_g200_terr_table.csv") %>% 
  clean_names() %>%
  filter(sq_km > 0) %>%
  group_by(objectid) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km))

#www
www_g200_terr <- read_csv("www_g200_terr_table.csv") %>% 
  clean_names() %>%
  filter(sq_km > 0) %>%
  group_by(objectid) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  mutate(sum_sq_km = sum(sq_km))

```

Biomes
```{r}

#global biomes
wwf_biomes <- read_csv("wwf_biomes.csv") %>% 
  clean_names() %>% 
  select(-area) %>% 
  mutate(strong_poly = strong_biomes_poly$total_strong) %>% 
  mutate(strong_km = strong_biomes_km$strong_km) %>%
  mutate(strong_perc = strong_km/sq_km) %>% 
  mutate(strong_www_poly = strong_www_biomes_poly$total_strong_www) %>% 
  mutate(strong_www_km = strong_www_biomes_km$strong_www_km) %>%
  mutate(strong_www_perc = strong_www_km/sq_km) %>%
  mutate(www_poly = www_biomes_poly$total_www) %>% 
  mutate(www_km = www_biomes_km$www_km) %>%
  mutate(www_perc = www_km/sq_km)

#strongholds
strong_biomes <- read_csv("strong_biomes.csv") %>% 
  clean_names() %>% 
  mutate(count = 1)

strong_biomes_poly <- strong_biomes %>% 
  group_by(name) %>% 
  summarise(total_strong = sum(count))

strong_biomes_km <- strong_biomes %>% 
  group_by(name) %>% 
  summarise(strong_km = sum(sq_km))

#strongholds with WWW
strong_www_biomes <- read_csv("strong_www_biomes.csv") %>% 
  clean_names() %>% 
  mutate(count = 1)

strong_www_biomes_poly <- strong_www_biomes %>% 
  group_by(name) %>% 
  summarise(total_strong_www = sum(count))

strong_www_biomes_km <- strong_www_biomes %>% 
  group_by(name) %>% 
  summarise(strong_www_km = sum(sq_km))

#www
www_biomes <- read_csv("www_biomes.csv") %>% 
  clean_names() %>% 
  mutate(count = 1)

www_biomes_poly <- www_biomes %>% 
  group_by(name) %>% 
  summarise(total_www = sum(count))

www_biomes_km <- www_biomes %>% 
  group_by(name) %>% 
  summarise(www_km = sum(sq_km))



```

Realms
```{r}

#global realms
wwf_realms <- read_csv("wwf_realms.csv") %>% 
  clean_names() %>% 
  na.omit() %>% 
  mutate(strong_poly = strong_realms_poly$total_strong) %>% 
  mutate(strong_km = strong_realms_km$strong_km) %>%
  mutate(strong_perc = strong_km/sq_km) %>% 
  mutate(strong_www_poly = strong_www_realms_poly$total_strong_www) %>% 
  mutate(strong_www_km = strong_www_realms_km$strong_www_km) %>%
  mutate(strong_www_perc = strong_www_km/sq_km) %>%
  mutate(www_poly = www_realms_poly$total_www) %>% 
  mutate(www_km = www_realms_km$www_km) %>%
  mutate(www_perc = www_km/sq_km)

#strongholds
strong_realms <- read_csv("strong_realms.csv") %>% 
  clean_names() %>% 
  mutate(count = 1) %>% 
  rename(sq_km = sq_km_16)

strong_realms_poly <- strong_realms %>% 
  group_by(realm) %>% 
  summarise(total_strong = sum(count))

strong_realms_km <- strong_realms %>% 
  group_by(realm) %>% 
  summarise(strong_km = sum(sq_km))

#strongholds with WWW
strong_www_realms <- read_csv("strong_www_realms.csv") %>% 
  clean_names() %>% 
  mutate(count = 1) %>% 
  rename(sq_km = sq_km_16)

strong_www_realms_poly <- strong_www_realms %>% 
  group_by(realm) %>% 
  summarise(total_strong_www = sum(count))

strong_www_realms_km <- strong_www_realms %>% 
  group_by(realm) %>% 
  summarise(strong_www_km = sum(sq_km))

#www
www_realms <- read_csv("www_realms.csv") %>% 
  clean_names() %>% 
  mutate(count = 1) %>% 
  rename(realm = realm_c_3)

www_realms_poly <- www_realms %>% 
  group_by(realm) %>% 
  summarise(total_www = sum(count))

www_realms_km <- www_realms %>% 
  group_by(realm) %>% 
  summarise(www_km = sum(sq_km))


```

Ecoregions
```{r}

#global ecoregions
wwf_terr_eco <- read_csv("wwf_terr_eco.csv") %>% 
  clean_names() %>% 
  select(-objectid) %>% 
  group_by(eco_name) %>% 
  summarise(sq_km = sum(sq_km)) %>% 
  full_join(strong_terr_eco_poly) %>% 
  full_join(strong_terr_eco_km) %>%
  mutate(strong_perc = strong_km/sq_km) %>% 
  full_join(strong_www_terr_eco_poly) %>% 
  full_join(strong_www_terr_eco_km) %>%
  mutate(strong_www_perc = strong_km/sq_km) %>%
  full_join(www_terr_eco_poly) %>% 
  full_join(www_terr_eco_km) %>%
  mutate(www_perc = strong_km/sq_km)

#strongholds
strong_terr_eco <- read_csv("strong_terr_eco.csv") %>% 
  clean_names() %>% 
  mutate(count = 1)

strong_terr_eco_poly <- strong_terr_eco %>% 
  group_by(eco_name) %>% 
  summarise(total_strong = sum(count))

strong_terr_eco_km <- strong_terr_eco %>% 
  group_by(eco_name) %>% 
  summarise(strong_km = sum(sq_km))

#strongholds with WWW
strong_www_terr_eco <- read_csv("strong_www_terr_eco.csv") %>% 
  clean_names() %>% 
  mutate(count = 1)

strong_www_terr_eco_poly <- strong_www_terr_eco %>% 
  group_by(eco_name) %>% 
  summarise(total_strong_www = sum(count))

strong_www_terr_eco_km <- strong_www_terr_eco %>% 
  group_by(eco_name) %>% 
  summarise(strong_www_km = sum(sq_km))

#www
www_terr_eco <- read_csv("www_terr_eco.csv") %>% 
  clean_names() %>% 
  mutate(count = 1) %>% 
  rename(sq_km = sq_km_32)

www_terr_eco_poly <- www_terr_eco %>% 
  group_by(eco_name) %>% 
  summarise(total_www = sum(count))

www_terr_eco_km <- www_terr_eco %>% 
  group_by(eco_name) %>% 
  summarise(www_km = sum(sq_km))

```

